#!/usr/bin/env bash
# KAP installer — panel+server (all-in-one) or edge server only.
set -euo pipefail

PREFIX="${PREFIX:-/opt/kap}"
SYSTEMD_DIR="${SYSTEMD_DIR:-/etc/systemd/system}"
SERVICE_USER="${SERVICE_USER:-kap}"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

RED=$'\033[0;31m'
GRN=$'\033[0;32m'
YLW=$'\033[0;33m'
NC=$'\033[0m'

info()  { echo "${GRN}[+]${NC} $*"; }
warn()  { echo "${YLW}[!]${NC} $*"; }
die()   { echo "${RED}[x]${NC} $*" >&2; exit 1; }

need_root() {
  if [[ "$(id -u)" -ne 0 ]]; then
    die "Run as root (sudo $0)"
  fi
}

have_cmd() { command -v "$1" >/dev/null 2>&1; }


prompt() {
  # $1=question $2=default
  local q="$1" d="${2:-}" ans
  if [[ -n "$d" ]]; then
    read -r -p "$q [$d]: " ans || true
    echo "${ans:-$d}"
  else
    read -r -p "$q: " ans || true
    echo "$ans"
  fi
}

prompt_secret() {
  local q="$1" ans
  read -r -s -p "$q: " ans || true
  echo
  echo "$ans"
}

choose_mode() {
  echo
  echo "Install mode:"
  echo "  1) all-in-one  — panel + KAP server in one process (recommended)"
  echo "  2) server-only — KAP edge node only (no panel; needs shared DB or legacy PSK)"
  echo
  local m
  m="$(prompt "Choose 1 or 2" "1")"
  case "$m" in
    1|all|all-in-one) echo "all" ;;
    2|server|server-only) echo "server" ;;
    *) die "invalid choice: $m" ;;
  esac
}

ensure_user() {
  if ! id -u "$SERVICE_USER" >/dev/null 2>&1; then
    info "Creating system user '$SERVICE_USER'"
    useradd --system --home "$PREFIX" --shell /usr/sbin/nologin "$SERVICE_USER" || true
  fi
}

list_existing_bins() {
  local missing=()
  for b in "$@"; do
    if [[ ! -x "$REPO_ROOT/bin/$b" && ! -f "$REPO_ROOT/bin/$b" ]]; then
      missing+=("$b")
    fi
  done
  if ((${#missing[@]})); then
    echo "${missing[*]}"
    return 1
  fi
  return 0
}

# Ensure required prebuilt binaries exist (no compile-from-source).
# $1 = mode (all|server)
prepare_binaries() {
  local mode="$1"
  local required=(kap-server)
  if [[ "$mode" == "all" ]]; then
    required=(kap-panel kap-server)
  fi

  local miss
  if ! miss="$(list_existing_bins "${required[@]}")"; then
    die "Missing binaries in $REPO_ROOT/bin/: $miss
Place release binaries there, for example:
  bin/kap-panel
  bin/kap-server
Then run this installer again."
  fi
  chmod +x "$REPO_ROOT/bin/"* 2>/dev/null || true
  info "Using binaries from $REPO_ROOT/bin/ (${required[*]})"
  ls -la "$REPO_ROOT/bin/" 2>/dev/null || true
}

install_files() {
  local mode="$1"
  info "Installing into $PREFIX"
  mkdir -p "$PREFIX"/{bin,data,decoy,etc}
  if [[ "$mode" == "all" ]]; then
    install -m 755 "$REPO_ROOT/bin/kap-panel" "$PREFIX/bin/kap-panel"
  fi
  install -m 755 "$REPO_ROOT/bin/kap-server" "$PREFIX/bin/kap-server"

  # decoy assets
  if [[ -d "$REPO_ROOT/decoy" ]]; then
    cp -a "$REPO_ROOT/decoy/." "$PREFIX/decoy/"
  fi

  # nginx example
  mkdir -p "$PREFIX/share"
  if [[ -f "$REPO_ROOT/deploy/nginx.conf.example" ]]; then
    install -m 644 "$REPO_ROOT/deploy/nginx.conf.example" "$PREFIX/share/nginx.conf.example"
  fi

  chown -R "$SERVICE_USER:$SERVICE_USER" "$PREFIX"
}

write_env_all() {
  local panel_listen="$1" kap_listen="$2" server_url="$3" admin_pass="$4" jwt_secret="$5"
  cat > "$PREFIX/etc/kap-panel.env" <<EOF
# Generated by install.sh — mode: all-in-one
KAP_DB=$PREFIX/data/kap.db
KAP_DECOY=$PREFIX/decoy
KAP_PANEL_LISTEN=$panel_listen
KAP_LISTEN=$kap_listen
KAP_SERVER_URL=$server_url
KAP_ADMIN_USER=admin
KAP_ADMIN_PASS=$admin_pass
KAP_JWT_SECRET=$jwt_secret
EOF
  chmod 640 "$PREFIX/etc/kap-panel.env"
  chown root:"$SERVICE_USER" "$PREFIX/etc/kap-panel.env"
}

write_env_server() {
  local kap_listen="$1" db_or_psk_mode="$2" value="$3"
  if [[ "$db_or_psk_mode" == "db" ]]; then
    cat > "$PREFIX/etc/kap-server.env" <<EOF
# Generated by install.sh — mode: server-only (shared DB)
KAP_DB=$value
KAP_LISTEN=$kap_listen
EOF
  else
    cat > "$PREFIX/etc/kap-server.env" <<EOF
# Generated by install.sh — mode: server-only (legacy global PSK)
KAP_PSK=$value
KAP_LISTEN=$kap_listen
EOF
  fi
  chmod 640 "$PREFIX/etc/kap-server.env"
  chown root:"$SERVICE_USER" "$PREFIX/etc/kap-server.env"
}

install_unit_all() {
  cat > "$SYSTEMD_DIR/kap-panel.service" <<EOF
[Unit]
Description=KAP Panel + embedded KAP server
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$SERVICE_USER
Group=$SERVICE_USER
EnvironmentFile=$PREFIX/etc/kap-panel.env
WorkingDirectory=$PREFIX
ExecStart=$PREFIX/bin/kap-panel \\
  -listen \${KAP_PANEL_LISTEN} \\
  -kap-listen \${KAP_LISTEN} \\
  -db \${KAP_DB} \\
  -decoy \${KAP_DECOY} \\
  -server-url \${KAP_SERVER_URL} \\
  -admin-user \${KAP_ADMIN_USER} \\
  -admin-pass \${KAP_ADMIN_PASS} \\
  -jwt-secret \${KAP_JWT_SECRET} \\
  -with-server
Restart=on-failure
RestartSec=3
LimitNOFILE=65535
# Hardening
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=$PREFIX/data $PREFIX/decoy
PrivateTmp=true

[Install]
WantedBy=multi-user.target
EOF
  systemctl daemon-reload
  systemctl enable kap-panel.service
  systemctl restart kap-panel.service
  info "systemd: kap-panel.service enabled and started"
}

install_unit_server() {
  cat > "$SYSTEMD_DIR/kap-server.service" <<EOF
[Unit]
Description=KAP edge server
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$SERVICE_USER
Group=$SERVICE_USER
EnvironmentFile=$PREFIX/etc/kap-server.env
WorkingDirectory=$PREFIX
ExecStart=/bin/sh -c 'if [ -n "\$KAP_DB" ]; then exec $PREFIX/bin/kap-server -listen "\$KAP_LISTEN" -db "\$KAP_DB"; else exec $PREFIX/bin/kap-server -listen "\$KAP_LISTEN" -psk "\$KAP_PSK"; fi'
Restart=on-failure
RestartSec=3
LimitNOFILE=65535
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=$PREFIX/data
PrivateTmp=true

[Install]
WantedBy=multi-user.target
EOF
  systemctl daemon-reload
  systemctl enable kap-server.service
  systemctl restart kap-server.service
  info "systemd: kap-server.service enabled and started"
}

rand_hex() {
  if have_cmd openssl; then
    openssl rand -hex "$1"
  else
    head -c "$1" /dev/urandom | od -An -tx1 | tr -d ' \n' | head -c "$(($1 * 2))"
  fi
}

print_summary_all() {
  local panel_listen="$1" kap_listen="$2" server_url="$3"
  cat <<EOF

${GRN}=== KAP all-in-one installed ===${NC}
  Prefix:     $PREFIX
  Panel:      http://${panel_listen}/
  KAP bind:   ${kap_listen}
  Public URL: ${server_url:-"(set KAP_SERVER_URL / -server-url)"}
  DB:         $PREFIX/data/kap.db
  Decoy:      $PREFIX/decoy
  Env:        $PREFIX/etc/kap-panel.env
  Unit:       systemctl status kap-panel

Login with the admin password you set.
Create a user in the panel and copy the client command shown there
(run kap-client on the *client* machine — it is not installed on the server).

Nginx example: $PREFIX/share/nginx.conf.example

Uninstall: sudo bash deploy/uninstall.sh  (or $PREFIX/../ if copied)
EOF
}

print_summary_server() {
  local kap_listen="$1"
  cat <<EOF

${GRN}=== KAP server-only installed ===${NC}
  Prefix:   $PREFIX
  KAP bind: ${kap_listen}
  Env:      $PREFIX/etc/kap-server.env
  Unit:     systemctl status kap-server

Point nginx at the KAP listen address for requests with sid= query.
EOF
}

# Inject "include <kap nginx conf>;" into nginx http { } block if nginx is present.
wire_nginx_include() {
  local conf_path="$1"
  local nginx_conf="${NGINX_CONF:-/etc/nginx/nginx.conf}"
  if ! have_cmd nginx; then
    warn "nginx not found — skip auto-include (install nginx later and re-run or add include manually)"
    return 0
  fi
  if [[ ! -f "$nginx_conf" ]]; then
    warn "nginx.conf not found at $nginx_conf — skip auto-include"
    return 0
  fi
  # Already included?
  if grep -qF "$conf_path" "$nginx_conf" 2>/dev/null; then
    info "nginx already includes $conf_path"
    return 0
  fi
  # Prefer conf.d drop-in if directory exists
  local conf_d="/etc/nginx/conf.d"
  if [[ -d "$conf_d" ]]; then
    local drop="$conf_d/kap-panel.conf"
    echo "include $conf_path;" > "$drop"
    info "Wrote $drop → include $conf_path"
  else
    # Insert before the last closing brace of http { } — simple approach:
    # append include on the line after "http {"
    if grep -qE '^\s*http\s*\{' "$nginx_conf"; then
      local bak="${nginx_conf}.bak.kap"
      cp -a "$nginx_conf" "$bak"
      # Insert include right after the first http {
      awk -v inc="    include $conf_path;" '
        BEGIN{done=0}
        {
          print
          if (!done && $0 ~ /^\s*http\s*\{/) {
            print inc
            done=1
          }
        }
      ' "$bak" > "$nginx_conf"
      info "Inserted include into $nginx_conf (backup: $bak)"
    else
      warn "Could not find http { in $nginx_conf — add manually: include $conf_path;"
      return 0
    fi
  fi
  if nginx -t 2>/dev/null; then
    systemctl reload nginx 2>/dev/null || nginx -s reload 2>/dev/null || warn "nginx reload failed — start nginx when ready"
    info "nginx config test OK"
  else
    warn "nginx -t failed after include — check $nginx_conf / $conf_path"
    nginx -t 2>&1 || true
  fi
}

main() {
  need_root

  local mode
  mode="$(choose_mode)"

  local panel_listen kap_listen server_url admin_pass jwt_secret
  kap_listen="$(prompt "KAP listen address" "0.0.0.0:8443")"

  if [[ "$mode" == "all" ]]; then
    panel_listen="$(prompt "Panel listen address" "0.0.0.0:8080")"
    server_url="$(prompt "Public KAP URL for client configs (e.g. https://cdn.example.com)" "")"
    admin_pass="$(prompt_secret "Admin password (first login)")"
    [[ -n "$admin_pass" ]] || die "admin password required"
    jwt_secret="$(rand_hex 32)"
    prepare_binaries all
    ensure_user
    install_files all
    write_env_all "$panel_listen" "$kap_listen" "$server_url" "$admin_pass" "$jwt_secret"
    install_unit_all
    # Generate a starter nginx include path (panel will overwrite on Apply)
    mkdir -p "$PREFIX/data"
    if [[ ! -f "$PREFIX/data/nginx-kap.conf" ]]; then
      cat > "$PREFIX/data/nginx-kap.conf" <<NGX
# Placeholder — open panel SSL/Nginx and press Apply to regenerate
NGX
    fi
    wire_nginx_include "$PREFIX/data/nginx-kap.conf"
    print_summary_all "$panel_listen" "$kap_listen" "$server_url"
  else
    echo
    echo "Auth mode for edge server:"
    echo "  1) Shared SQLite DB path (same file as panel host, e.g. NFS)"
    echo "  2) Legacy single global PSK"
    local am
    am="$(prompt "Choose 1 or 2" "1")"
    local value
    if [[ "$am" == "1" ]]; then
      value="$(prompt "Path to shared kap.db" "$PREFIX/data/kap.db")"
      prepare_binaries server
      ensure_user
      install_files server
      write_env_server "$kap_listen" db "$value"
    else
      value="$(prompt_secret "Global PSK (hex or string)")"
      [[ -n "$value" ]] || die "PSK required"
      prepare_binaries server
      ensure_user
      install_files server
      write_env_server "$kap_listen" psk "$value"
    fi
    install_unit_server
    print_summary_server "$kap_listen"
  fi
}

main "$@"
